### PR TITLE
fix PropTypes

### PR DESCRIPTION
**Pull request by borm**

### CODE REVIEW

**Comment by alexkuz** [comment]
Please revert "add build" commit, the build is not supposed to be in repository. Thank you!

**Comment by borm** [comment]
reverted

**Comment by mbifulco** [comment]
@alexkuz is this PR waiting on anything else? It looks like the `add build` commit you were talking about must have been reverted.

**Comment by alexkuz** [comment]
@mbifulco I think I'll merge and publish it tomorrow

**Comment by mbifulco** [comment]
Thank you!
thank you

**Comment by alexkuz** [comment]
Published in v0.10.8

**Pull request merged**
